### ISSUE TITLE
Manual balancing option

### ISSUE THREAD

**Issue by specing** [Yaribz/SPADS#16]
Would it be possible to add a balance "command" that completely bypasses the autobalancer?

e.g. !balance {player1, player2, player3} {player4, player5 + player6}

This would achieve: players 1,2,3 on ally team 1
player 4,5,6 on ally team 2, players 5 and 6 share team-id

**Comment by Yaribz** [comment]
Well, imo you can't balance manually *and* have autobalance enabled at the same time.

Either you have autobalance enabled (and you can tune it with different balancing modes, clans etc.), *or* you balance manually so that you have full control on each team.

However, I agree that a manual balance command which would replace a sequence of "!force ... team/id ..." commands might be useful *when autobalance is disabled*.

So in your example "!balance {player1, player2, player3} {player4, player5 + player6}" would just behave as if you had typed:

    !force player1 id 1
    !force player1 team 1
    !force player2 id 2
    !force player2 team 1
    !force player3 id 3
    !force player3 team 1
    !force player4 id 4
    !force player4 team 2
    !force player5 id 5
    !force player5 team 2
    !force player6 id 5
    !force player6 team 2

But it would only works if autobalance is disabled.

Is that the functionality you're looking for?

**Comment by specing** [comment]
yes.

**Comment by specing** [comment]
could also add colours:

!balance {player1#yellow, player2#ff00aa, player3} {player4, player5 + player6}#00ff00

the later would cause all in ally-team 2 to have different shades of green.

**Comment by Yaribz** [comment]
The functionality has actually been integrated as a new syntax of the !force command, because it does behave like a sequence of "!force" commands (when autohost admins allow players to use the !balance command, it is only because they want them to be able to auto-balance the battle according to current balance mode, they usually don't want them to be able to manually force the balance using the same command).
Concerning color forcing, I don't think it is very useful because colors are usually auto-fixed, so I will spend my time on other improvements...
