### ISSUE TITLE
"Disconnecting from lobby server (broken connection detected)"

### ISSUE THREAD

**Issue by abma** [Yaribz/SPADS#31]
when and why does this happens?

log of such an event:

http://paste.springfiles.com/view/raw/09a6f10b

**Comment by Yaribz** [comment]
just look at the warning or error lines:

20170918224255 - ERROR    - [SpringLobbyInterface] Ignoring CLIENTSTATUS command (unknown user:"[ACE]Ticot")
20170918224255 - WARNING  - [SPADS] Unable to store data for user "[ACE]Ticot" (user unknown)

=> 

20170918224256 - WARNING  - [SPADS] Disconnecting from lobby server (broken connection detected)

According to the log you provided the lobby server sent a "CLIENTSTATUS" command before the "ACCEPTED" command. This doesn't make sense of course, the corresponding client ([ACE]Ticot) hasn't even been declared to SPADS yet. => inconsistency detected => broken connection

**Comment by abma** [comment]
oh, that helps. thanks!

**Comment by springraaar** [comment]
Note, today spads hosts on the official server got disconnected due to these inconsistency check failures that get triggered by some event related to another host

20231214221049 - WARNING  - [SpringLobbyInterface] Ignoring duplicate ADDUSER command for user "[HAK]Host2"
20231214221049 - WARNING  - [SPADS] TrueSkill service unavailable!
20231214221049 - WARNING  - [SPADS] Disconnecting from lobby server (broken connection detected)
20231214221049 - NOTICE   - [SpringLobbyInterface] Disconnecting from lobby.springrts.com:8200

This has been happening today and it happens every few months.

Maybe it's a bug on the official server's side but anyway spads itself shouldn't just disconnect and exit!

Tizbac suggested editing spads.pl and changing the inconsistencyHandler assignment of $lobbyBrokenConnection=0 (lines 500 and 15538) to prevent this disconnection behavior from SPADS side and it's been working.

**Comment by Yaribz** [comment]
> Maybe it's a bug on the official server's side but anyway spads itself shouldn't just disconnect and exit!

You have a SPADS instance that exited due to the lobby server sending inconsistent command ? You're right that shouldn't be the case, SPADS is supposed to do the only thing it can do to workaround a bug in the lobby server: disconnect and reconnect in the hope that the lobby server send consistent data this time.
Are you sure there isn't any line indicating a (re)connection attempt after the lines you pasted here ?

**Comment by Yaribz** [comment]
> Maybe it's a bug on the official server's side but anyway spads itself shouldn't just disconnect and exit!

Indeed SPADS shouldn't exit in this case, it should just reconnect to the lobby server in the hope that the lobby server send consistent data this time. I can't reproduce the problem on my system unfortunately, but I will try to take a look anyway.

**Comment by springraaar** [comment]
it seems that as of version 0.13.31, the issue is, in fact, still there.

A user was starting his spads host which connects to springrts.com but it'd disconnect immediately because of this:

NOTICE   - [SPADS] Spring server mode: dedicated
NOTICE   - [SimpleEvent] Event loop initialized using internal model (time slice: 500ms)
NOTICE   - [SimpleEvent] Starting event loop...
NOTICE   - [SpringLobbyInterface] Connecting to lobby.springrts.com:8200
NOTICE   - [SpringLobbyInterface] TLS enabled (TLSv1_3,TLS_AES_256_GCM_SHA384)
WARNING  - [SpringLobbyInterface] Ignoring duplicate ADDUSER command for user "[HAK]Host1"
WARNING  - [SPADS] The lobby account currently used by SPADS is not tagged as bot. It is recommended to ask a lobby administrator for bot flag on accounts used by SPADS
WARNING  - [SPADS] Disconnecting from lobby server (broken connection detected)
NOTICE   - [SpringLobbyInterface] Disconnecting from lobby.springrts.com:8200

Editing spads.pl as suggested in previous posts fixed his issue.

**Comment by Yaribz** [comment]
Your message is unclear to me.

Did SPADS exit / quit / stop functioning, or did it just disconnect automatically from the lobby server and attempted reconnection after the configured [lobbyReconnectDelay](http://planetspads.free.fr/spads/doc/spadsDoc_All.html#global:lobbyReconnectDelay) delay ?

**Comment by springraaar** [comment]
There don't seem to be any uberserver devs still active/willing to fix this on their side.

Spads disconnects. Not sure if his case would try to reconnect later, but it wouldn't fix the issue : the Ace spads hosts have been reconnecting and disconnecting immediately over and over for the same reason.

Spads reaction to the lobby bug makes it unusable (until the lobby server is restarted, i think). Disabling the consistency check there doesn't seem to have had any negative consequences as the hosts keep going for days and weeks in those conditions.

You could put a comment in saying it's a temporary workaround for a lobby server bug.

**Comment by Yaribz** [comment]
> Spads disconnects. Not sure if his case would try to reconnect later

Then I see no issue at SPADS side. It is the expected behavior to just reconnect to the lobby server in the hope that the lobby server sends consistent data this time.

> Spads reaction to the lobby bug makes it unusable

Unfortunately I don't have enough free time to make SPADS work with a lobby server sending inconsistent data. And I can offer no support to anyone using a SPADS instance with consistency checks disabled, as it is a nightmare to debug (these checks have been added after having wasted way too much of my time investigating on SPADS bug reports which actually ended up being lobby server bugs). 
> Disabling the consistency check there doesn't seem to have had any negative consequences as the hosts keep going for days and weeks in those conditions.

Sure it will seem to work, until some random bugs (seemingly unrelated) occur here and there. The correct action is to fix the bug in the lobby server, not make SPADS work in a degraded and undebuggable mode.
