### ISSUE TITLE
NewFeature : Add «pr-downloader»

### ISSUE THREAD

**Issue by FabriceFABS** [Yaribz/SPADS#39]
Hey !

What about adding «`pr-downloader`» "exe/bin" into var/spring/10x path in your automanagement ENGINE system for using it ?
I use (actually 103) `pr-downloader` with a cron job for automatic MOD update.

Yes I know I can get 104 ENG package 7zip on springrts.com, extracting it somewhere, and make a link. This is what a do actually with 103 ENG.

It's just a question ! ;)

**Comment by Yaribz** [comment]
Hey,

It's not planned to include pr-downloader binary in the list of files extracted for each Spring version hosted, because it's not required for hosting. Also, as I understand it, it doesn't really make sense to download multiple versions of this binary, only the last working versions is useful.

Automatic downloading/updating of the latest pr-downloader binary would make more sense in a plugin which would be in charge of auto-updating games/mods for example.
