### ISSUE TITLE
teams consisting greater than 8 havent trueskill sorting right

### ISSUE THREAD

**Issue by Ruwetuin** [Yaribz/SPADS#42]
normally playerid s are given to the highest ranked players and then to the lower ones. But this is not the case when teams have more than 8 players

See advplayerlist ingame:
https://i.imgur.com/hB9PtBA.png

**Comment by Yaribz** [comment]
This is due to the lobby server not supporting more than 16 player/team IDs. There is a workaround in SPADS for this limitation (so that it's still possible to play team games bigger than 8v8), but in this case player IDs aren't sorted as you might expect (even if afaik this is not mandatory for autohosts to sort player IDs according to skill...). I might improve the workaround in the future to fix this with some not-so-clean code in SPADS though :/

**Comment by Yaribz** [comment]
Finally improved the workarounds for lobby protocol limitations, which should fix this issue at the same time.
