### ISSUE TITLE
autolockclients matters even when autolock is off

### ISSUE THREAD

**Issue by silentwings** [Yaribz/SPADS#44]
It looks to me as though https://github.com/Yaribz/SPADS/blob/master/src/spads.pl#L2045 will trigger and autolock the battle whenever nbClients > conf{autoLockClients}, even if conf{autoLock} itself is set to off. By default, according to http://planetspads.free.fr/spads/doc/spadsDoc.html this will bite as soon as there are 32 or more clients connected.

I'm not sure if this effect was intended, but if I'm right then I think it has confused the current BA hosters.

**Comment by Yaribz** [comment]
This is indeed the expected behavior.

The purpose of the "autoLockClients" setting is really to allow autohost admins to limit the maximum number of clients (players and spectators) using their autohost at the same time, because they know their network connection can't handle more than that without degrading performance.

On the other hand, the "autoLock" setting is just a way to configure SPADS behavior regarding battle structure automanagement. It only takes players into account.

These two settings have different goals and autohost admins might want to disable one while still using the other one. For example it is usefull for autohost admins to be able to disable "autoLock" (because they want the battle room to stay open even when the target number of players is reached, so that spectators can join directly without using !unlockSpec), and still use "autoLockClients" to avoid network congestion.

I might need to update SPADS documentation to make that clearer.
Also, I guess the default value for autoLockClients should be increased a bit...
