### ISSUE TITLE
support for KICKFROMBATTLE:server

### ISSUE THREAD

**Issue by silentwings** [Yaribz/SPADS#45]
As discussed - KICKFROMBATTLE now exists not just in the host->server direction but also in the server->host direction (currently only on the test lobbyserver)

https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L2757

**Comment by Yaribz** [comment]
I started implementing this, but if I understand correctly the lobby server will only send the KICKFROMBATTLE command if the client is in a battleroom while being kicked from lobby server. So basically one would just need to leave the battleroom as soon as the game has started to protect himself from being kicked from game by lobby server?

**Comment by silentwings** [comment]
I realized this issue as well - the lobby wil simply remember the most recent battle client was in (whether logged in or not) but I haven't implemented this yet.

**Comment by Yaribz** [comment]
I'm not sure the battle_id parameter is really needed actually. I think SPADS will just ignore it because it's entirely possible that the battle lobby has been rehosted (thus changing the battle ID) while a game is in progress and SPADS doesn't keep previous battle IDs in memory.
Basically when SPADS receives a KICKFROMBATTLE command it will just check that a game is in progress and userName is allowed to connect to this game (he can be already connected or not yet connected). Only in this case it will perform a one-game kickBan for this user.

**Comment by silentwings** [comment]
The battle_id is only included in preparation for a future version of the protocol, not planned any time soon, which could allow users (& particularly hosts) to be present in multiple battles at once. Ignoring it is fine.

**Comment by Yaribz** [comment]
You mean there could be cases where a player is in two games hosted by same autohost simultaneously and an admin could want to kickban this player from one game but not from the other one ?

**Comment by silentwings** [comment]
I appreciate its unlikely to want that particular thing - but essentially yes. I'm sticking to a general principle that protocol commands relating to battles should specify which battle they relate to.

**Comment by Yaribz** [comment]
implemented in SPADS 0.12.5 ( 2cab8ef )
