### ISSUE TITLE
installer not working in non interactive mode

### ISSUE THREAD

**Issue by cghislai** [Yaribz/SPADS#48]
The installer fails in non-interactive mode due to the last 3 questions:

```
$conf{lobbyLogin}=promptString("$currentStep/$nbSteps - Please enter the autohost lobby login (the lobby account must already exist)");
$currentStep++;
$conf{lobbyPassword}=promptString("$currentStep/$nbSteps - Please enter the autohost lobby password");
$currentStep++;
$conf{owner}=promptString("$currentStep/$nbSteps - Please enter the lobby login of the autohost owner");
$currentStep++;
```

These statements should be run only if the $conf entries are empty and the installer is running in interactive mode. So that we can pass them as arguments or edit the config file afterwards.

**Comment by cghislai** [comment]
workaround:
```
 perl spadsInstaller.pl 
 sed -i 's/^\$conf{lobbyLogin}.*$//' spadsInstaller.pl 
 sed -i 's/^\$conf{lobbyPassword}.*$//' spadsInstaller.pl 
 sed -i 's/^\$conf{owner}.*$//' spadsInstaller.pl 
 sed -i 's/spadsInstaller\.pl //' spadsInstaller.pl 
 perl spadsInstaller.pl
```

**Comment by Yaribz** [comment]
I'm not sure I understand your request. Why don't you just use the standard way of passing STDIN arguments to programs in non-interactive mode instead of patching the binary ?

In your case, for the 3 parameters which seem to cause you trouble:

    echo "lobbyLoginValue
    lobbyPasswordValue
    ownerValue" | perl spadsInstaller.pl

**Comment by cghislai** [comment]
This is indeed another way to work around that. I tried using \n rather than an actual line break which is probably why it failed and I opted for sed. It would be nice if that workaround was not mandatory though.

**Comment by Yaribz** [comment]
I don't understand why you call that a workaround ? The installer isn't supposed to be used in a non-interactive way, however you can use it this way as any other console program, by piping inputs.

**Comment by Yaribz** [comment]
I don't understand why you call that a workaround ? The installer isn't supposed to be used in a non-interactive way for full SPADS install, however you can use it this way as any other console program, by piping inputs.

**Comment by cghislai** [comment]
Ok looking at the code, i saw that there was a nonInteractive variable used in most place except those 3, thus I thought this was a supported feature and that those 3 last input not working was a bug.
If this is not supported then thats ok this can be closed

**Comment by Yaribz** [comment]
Ah ok I understand now. Actually there is indeed some special handling for non-interactive mode, in order to avoid being stuck in re-ask loop in case of invalid value provided, but that's about all.

I think you might have been confused by a mechanism in place which allows the installer to relaunch itself during auto-updates and library path adjustments for example. This mechanism makes it possible to start the installer from a specific step without re-asking the questions from the beginning. In this case indeed some configuration values are passed as parameters so that they don't need to be re-asked to the user, but it's just internal functioning not officially exposed to the end user. That's why this mechanism doesn't handle the parameters you listed: the installer doesn't need to restart itself once it has reached these steps.
