### ISSUE TITLE
 [SPADS] Unable to create temporary directory "/.InlinePython.tmp" for Inline::Python used by plugin SpadsPluginApi: Permission denied

### ISSUE THREAD

**Issue by Beherith** [Yaribz/SPADS#54]
I tried looking through the source, and it seems that the catdir func is not getting anything for instanceDir, so it is trying to create a temp directory in root (which naturally wont succeed :) ). InstanceDir is defined in my main spads.conf as:

https://github.com/Yaribz/SPADS/blob/e258204ffc1d84b7e8865c47b1e73a8c79275d92/src/SpadsPluginApi.pm#L54

My spads.conf:

# SPADS files
etcDir:etc
varDir:var
instanceDir:spads_host14
logDir:log

the spads_host14 folder exists and is rwxrwxrwx

Thank you for looking into this!

**Comment by Yaribz** [comment]
Mmm that's very weird, it's like SPADS wasn't entirely initialized when it tries to load the plugin...

Can you give some context: is it something which happens when you try to load a Python plugin manually (`!plugin ... load`) or when you try to load it automatically with the `autoLoadPlugins` setting ?

**Comment by Yaribz** [comment]
Mmmm I think I know what happened, working on it...
Meanwhile you can try to load the Python plugin manually with `!plugin ... load` instead of using the `autoLoadPlugin` setting.

**Comment by Yaribz** [comment]
fixed in SPADS 0.12.31, thanks for the report !
