### ISSUE TITLE
Return zero error code when spads failed

### ISSUE THREAD

**Issue by p2004a** [Yaribz/SPADS#63]
When spads fails to connect to the lobby,

```
Jul 31 18:56:59 87a826e59173 spads_cluster_launcher.sh[12043]: 20230731185659 - ERROR    - [SPADS] Login denied on lobby server (Invalid password)
```

the spads exits, but returns code 0, which means success. What I expect it return a non-zero exit status when it exits because of error.

**Comment by Yaribz** [comment]
SPADS currently returns non-zero exit code when the failure is due to SPADS itself or its configuration (for example if a library cannot be loaded, or if the configuration is invalid...).
When the lobby server says the password is invalid, SPADS itself is actually working correctly and its configuration is syntactically correct, so it's a different level of error. I will see what I can do to return exit code 2 in such case...

**Comment by Yaribz** [comment]
Actually I revamped SPADS exit code management, the exit codes can be found [here](https://github.com/Yaribz/SPADS/blob/605121/src/spads.pl#L59-L75).
For example the exit code in case of login denied is now `50`.

**Comment by p2004a** [comment]
Great! Thanks a lot!
